---
project: CMBU on CMBU
kind: PIPELINE
name: wavefront-actions-send-metrics-010-sample
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAYFBMVEX///85rOInqOHu9/zD4/Wq1/EvqeEhpuDM5/bG5PXz+v2a0O7v+Pzj8vqe0u/K5vbX7PiLyuy63vOx2vJZt+ZGseR3wunn9PtduOaBxutrvejb7vl8xOr4/f5Os+QAot+pplYAAAAF1UlEQVR4nO3d65KqMAwA4KVgUXRZr+tt1fd/y9OCx12BSkqKTTvJzzOzGb7BA6Vp04+PmOJz8z3xfQ3jhdIluRCRCvfrH6WTSZLEKEzXx0RUuiRCYZodd/lDF5twka0aupiExWx1betiERZf86vIu3RRCKfzrei8dzEIL8vy0P3LjEK4LE+yVxes8Dw59d+7YIVKlwgJ5QUn/PxO4DcvSGGW2+kCFAoWspB6sJCF9IOFLKQfLGQh/WAhC+kHC1lIPyITnientPFPhIRp89osoy7f5kSFxWy1u2XD/17p5L18S1B4uZeBxEDhb3E6ISgspvNtfi9yDRHu18fGfC8p4bI8/C2U2ArT9XHXLpKRES7LU/PqbITpuqs4TUaoHumyo1ACFaadpXcyQl0GyrvLQBDhIjOV3kkI9SP9RXW5T6jfKObSu3fh8yPdWqjeKI9nLkFh+5FuJVRvlCtM50W46Hykw4XqfQkrvXsRdq83ggsvc8CyiVaWdwn1eqP+x8Jz2qYwtfv7e5Y3CTc3+6trCwdc29uEkyFpWQjLwkJQEhay0JCWhbAsLAQlYSELDWlZCMvCQlASFrLQkJaFsCwsBCVhIQsNaVkIy8JCUBIWstCQloWwLCwEJWEhCw1pWQjLwkJQEhay0JCWhbAsLAQlYSELDWlZCMvCQlASFrLQkJaFsCwsBCVhIQsNaVkIy8JCUBIWstCQloWwLGihFPIwjVYoRX4ol5deX5hCKcSh7L95gQplLq7zaQHlBSaUeb5dzWx0IQnV/7udvS4UYaXLhrYboS5UT5XdcY1ppkJZqO5dclzvETrKQq373nwidVSFSifc6CgKpcyT0+TsSEdNmKubd5osHeqoCbelax0x4UjBQuLCRf8T15dQihtWWMxW2xvNb3wHbwTdKKZqrEZQWL8RIB/nxpiWh/99ZqgJ9cQK7o3QPF+HkrCaesDdu7r12POlEBFq3XyK1YmuxmoEhEp3Reo+N6fE0ODJt1BPrMy/hkw9/NG9PF/Hp1BPiq1wOt1Yrac5ly9hPW20wOh0N0lIYzUPQj2xsspwumzVd+98CfXUw/BJsSqKbHUF6t4t1L9M3KRY1W/Rsu/b24S5cDApNrPvavc2YeFk2mikU8mcCN0E5QopCzvj3BzJURHq6VpwddIUeizW+sYnIZQCP137fyxGb6WCGkZjP/B0k9vHG4+WUA3FtshPoOrI8KfPczJCpUuQA82qs3er7zkJoR5o/iAHK6a+5f6FUgp5Qg5Wqha+hrGYZ6GDKpD5QHTvwvqxgtPpkzB6xtGehMMXdTzi0nsgujdh/YWHemhepiVI50EoJb503jjng5JQPzRxYzHYYfaehLnYYsdiHwvLpu5vFU5nSJ0O0muEnQQLQxOeWyXAmIRnXShpnUoWi/Bxvo7vdd6jCPfrn99PoOiEzY/zuIRdH+fxCFNToSQKYfH14nyd4IV/jzqMTwj6fA1XuPxdTfU6bZDCekUOMG1wwhdHHXanDUq433wLG12VNijhZMjXeVhCOqugWdiZJHKhzG+beIXVykDI7HyQwnrLJXB2PjhhveXSovYQlHDQlstghIPL0UEI9QTY4LoReWG1wWaDqBuRFkp8VYyyUP00Ty62XNIU4rcPURZWmzSsenuEJKw6l3w5qGgSFd6wy0CoC9NxNgYTEo4ULGQhC1nIQhaykIUsZCELWchCFrKQhRihg15fIwpzbK8v4aIFw1jCqq9oswpkIayLZK46d7oWSr2Vu6sMBBTqe+euL6lzYbXn0lAGAgjVnw8vAaICJNRFrleFkh6h/mW67bpqE71CSAP7F0Kpi2TedDpeCqH7ZY29vnSBc4yuqzZhFNZlIFihpLPXV1XgdFtGGhSdQvXLhK03uke715dwVuBER0totd7oHo1eX9sS2WDCaTwJq73OA3p1/en1he2P6D4ewnooNWysWPf6wjcHGSUqIbb9RXrLsR0Ex4uJcNDAvsiI6nRM/Aylxot/K3miFUOVeWoAAAAASUVORK5CYII=
enabled: true
description: Pipeline to send metrics to wavefront. This is part of wavefront-actions in codestream-actions-kit.
concurrency: 10
input:
  METRIC_NAME: ''
  METRIC_VALUE: ''
  POINT_TAGS: ''
  SERVER_URL: ''
  SOURCE: ''
  TIMESTAMP: ''
  TOKEN: ''
_inputMeta:
  METRIC_VALUE:
    description: ''
    mandatory: true
  TIMESTAMP:
    description: ''
    mandatory: true
  SOURCE:
    description: ''
    mandatory: true
  SERVER_URL:
    description: ''
    mandatory: true
  TOKEN:
    description: ''
    mandatory: false
  METRIC_NAME:
    description: ''
    mandatory: true
  POINT_TAGS:
    description: ''
    mandatory: true
workspace:
  type: DOCKER
  endpoint: cat-custom-integration-docker-host-vm
  image: cmbucicd/wavefront-actions:0.1.0
  registry: wavefront-actions-registry
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Send Metric
stages:
  Send Metric:
    taskOrder:
    - Send Custom Metric
    tasks:
      Send Custom Metric:
        type: Custom
        input:
          name: Wavefront Actions
          version: 0.1.0
          properties:
            server_url: ${input.SERVER_URL}
            token: ${var.Symphony-Wavefront-Token}
            action: sendCustomMetric
            metric_name: ${input.METRIC_NAME}
            metric_value: ${input.METRIC_VALUE}
            timestamp: ${input.TIMESTAMP}
            source: ${input.SOURCE}
            point_tags: ${input.POINT_TAGS}
